CREATE TABLE public.user_accounts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username VARCHAR(255),
      email VARCHAR(255) NOT NULL UNIQUE ,
      password VARCHAR(255) NOT NULL,
      employee_id BIGINT,
      client_id BIGINT,
      role VARCHAR(64),
      CONSTRAINT fk_user_employee_id FOREIGN KEY (employee_id) REFERENCES public.employee(id),
      CONSTRAINT fk_user_client_id FOREIGN KEY (client_id) REFERENCES public.client(id)
);

CREATE TABLE public.token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_token VARCHAR(255),
    refresh_token VARCHAR(255),
    is_logged_out BOOLEAN,
    user_account_id BIGINT,
    CONSTRAINT fk_user_account_id FOREIGN KEY (user_account_id) REFERENCES public.user_accounts(id)
);